spring:
  datasource:
    url:
    username:
    password:

    druid:
      stat-view-servlet:
        login-username: mytest
        login-password: 123456
      initial-size: 5
      min-idle: 10
      max-active: 20

#OSS配置
image-properties:
  endpoint:
  keyid:
  keysecret:
  bucketname: