spring:
    datasource:
      url: jdbc:mysql://192.168.154.129:3306/imagehosting?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

      druid:
        stat-view-servlet:
          login-username: mytest
          login-password: 123456
        initial-size: 5
        min-idle: 10
        max-active: 20

#OSS配置
image-properties:
  endpoint:
  keyid:
  keysecret:
  bucketname: